name: unittests

on:
  pull_request:
  push:
    branches:
      - main

jobs:

  unit:
    runs-on: ubuntu-latest
    container: golang:1.19

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build server binary
        run: |
          go test -race -coverprofile=coverage.out -covermode atomic ./...

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
          env: CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          file: ./coverage.out
          flags: unit
          name: unit